INSERT INTO SOCS (NOMBRE, PAIS, NIVEL_SEGURIDAD, AUTOR_EXAMEN)
VALUES ('SOC Barcelona', 'ESPAÑA', 85, 'ENMA CONTIN');

INSERT INTO SOCS (NOMBRE, PAIS, NIVEL_SEGURIDAD, AUTOR_EXAMEN)
VALUES ('SOC Londres', 'REINO UNIDO', 99, 'ENMA CONTIN');

INSERT INTO SOCS (NOMBRE, PAIS, NIVEL_SEGURIDAD, AUTOR_EXAMEN)
VALUES ('SOC Valencia', 'ESPAÑA', 70, 'ENMA CONTIN');


INSERT INTO INCIDENTES (CODIGO_INCIDENTE, TIPO_INCIDENTE, FECHA_DETECCION, ESTADO, AUTOR_EXAMEN, FK_SOC_ID)
VALUES ('INC-002', 'Ransomware', '2026-06-05', 'CERRADO', 'ENMA CONTIN', 1);

INSERT INTO INCIDENTES (CODIGO_INCIDENTE, TIPO_INCIDENTE, FECHA_DETECCION, ESTADO, AUTOR_EXAMEN, FK_SOC_ID)
VALUES ('INC-003', 'Fuga de Datos', '2026-06-06', 'ABIERTO', 'ENMA CONTIN', 2);

INSERT INTO INCIDENTES (CODIGO_INCIDENTE, TIPO_INCIDENTE, FECHA_DETECCION, ESTADO, AUTOR_EXAMEN, FK_SOC_ID)
VALUES ('INC-004', 'Ataque de Fuerza Bruta', '2026-06-07', 'EN INVESTIGACIÓN', 'ENMA CONTIN', 3);

INSERT INTO INCIDENTES (CODIGO_INCIDENTE, TIPO_INCIDENTE, FECHA_DETECCION, ESTADO, AUTOR_EXAMEN, FK_SOC_ID)
VALUES ('INC-005', 'Inyección SQL', '2026-06-08', 'CERRADO', 'ENMA CONTIN', 1);